### ISSUE TITLE
Fluxo do Usuário

### ISSUE THREAD

**Issue by pauloosilas** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t2-encontre-aqui#2]
[Fluxo do Usuário](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t2-encontre-aqui/issues/2)

**Comment by PedroItalocv** [comment]
**Teste.**
